cd_name_array = [
  "タカオニ/カンケリ",
  "young animal e.p.",
  "GOOD TIME!",
  "YOUNG KING",
  "今日から明日",
  "スーパーオリジナル",
  "イツナロウバ",
  "カンケリ01/LIFELINE",
  "GREATEST HITS",
  "クリスマス・イブRap",
  "マルシェ",
  "VITALIZER",
  "ONEWAY",
  "sayonara sayonara",
  "アンバランス",
  "地球ブルース～337～/DJDJ [for RADIO]",
  "TORIIIIIICO!",
  "magic number",
  "性コンティニュー",
  "GOOD MUSIC(シングル)",
  "パンク寸前のFUNK",
  "ナビ/揺れ",
  "脳内VACATION",
  "BEST ALBUM 2001-2003",
  "GOOD MUSIC(アルバム)",
  "KICK!",
  "住所 feat. 岡村靖幸",
  "希望の炎",
  "音色",
  "ひとりじゃないのよ",
  "新人クレバ",
  "ファンキーグラマラス feat.Mummy-D(マボロシ/Rhymester)",
  "イッサイガッサイ",
  "スタート",
  "国民的行事",
  "愛・自分博",
  "Have a nice day!",
  "THE SHOW",
  "アグレッシ部",
  "くればいいのに feat. 草野マサムネ from SPITZ[Single Edit]",
  "よろしくお願いします",
  "ストロングスタイル",
  "青",
  "クレバのベスト盤",
  "赤",
  "心臓",
  "OASYS",
  "挑め",
  "C'mon, Let's go",
  "KILA KILA / Tan-Kyu-Shin",
  "GO",
  "Na Na Na",
  "王者の休日",
  "SPACE",
  "BESHI",
  "トランキライザー",
  "Under The Moon",
  "嘘と煩悩",
  "存在感",
  "いいの",
  "CHILD PLAY",
  "Mr.COMPACT",
  "I SING, I SAY",
  "聖者が街にやってくる",
  "はつ恋の~What's Going on~ feat.トータス松本",
  "LIFE",
  "ワンマンショウ",
  "夢のせい",
  "アカリタイトル1",
  "アカリタイトル2",
  "幸せであるように",
  "サーフライダー",
  "ありがとう",
  "A Peacetime MCU",
  "MCU in WONDERLAND e.p.",
  "nukumori",
  "omoide",
  "サヨナラ",
  "A.K.A",
  "SUPERSTAR",
  "SHU・HA・RI ~STILL LOVE~",
  "ギミギミ・ナイトフィーバー",
  "BEST OF MCU",
  "Roots",
  "Angel",
  "ウワサの真相",
  "この街のどこかに/さとうきび畑",
  "Beginning of the Endless",
  "シーサイド・ばいばい",
  "OH YEAH",
  "\"YES\"rhyme-dentity"
]

cd_img_array = [
  "takaoni",
  "younganimal",
  "goodtime",
  "youngking",
  "kyoukaraashita",
  "superoriginal",
  "itsunarouba",
  "kankeri01",
  "greatesthits",
  "christmaseverap",
  "marche",
  "vitalizer",
  "oneway",
  "sayonarasayonara",
  "unbalance",
  "chikyuublues",
  "toriiiiiico",
  "magicnumber",
  "sagacontinue",
  "goodmusic_sg",
  "puncsunzennofunk",
  "navi",
  "nounaivacation",
  "bestalbum20012003",
  "goodmusic_al",
  "kick",
  "juusho",
  "kibounohonoo",
  "neiro",
  "hitorijanainoyo",
  "shinjinkreva",
  "funkyglomorous",
  "issaigassai",
  "start",
  "kokumintekigyouji",
  "aijibunhaku",
  "haveaniceday",
  "theshow",
  "aggressibu",
  "kurebaiinoni",
  "yoroshikuonegaishimasu",
  "strongstyle",
  "ao",
  "krevanobestban",
  "aka_kreva",
  "shinzou",
  "oasys",
  "idome",
  "cmonletsgo",
  "kilakila",
  "go",
  "nanana",
  "oujanokyuujitsu",
  "space",
  "beshi",
  "tranquilizer",
  "underthemoon",
  "usotobonnou",
  "sonzaikan",
  "iino",
  "childplay",
  "mrcompact",
  "isingisay",
  "seijagamachiniyattekuru",
  "hatsukoino",
  "life",
  "onemanshow",
  "yumenosei",
  "akalititle1",
  "akalititle2",
  "shiawasedearuyouni",
  "surfrider",
  "arigatou",
  "apeacetimemcu",
  "mcuinwonderland",
  "nukumori",
  "omoide",
  "sayonara",
  "aka_mcu",
  "superstar",
  "shuhari",
  "givmegivmenightfever",
  "bestofmcu",
  "roots",
  "angel",
  "uwasanoshinsou",
  "konomachinodokokani",
  "beginningoftheendless",
  "seasidebyebye",
  "ohyeah",
  "yesrhymedentity"
]

cd_name_array.each_with_index do | name, index |
  cd = Cd.find_by(name: name);
  if cd
    cd.img_name = cd_img_array[index]
    cd.save
  else
    p '見つからない -> ' + name
  end
end

# cd = Cd.find_by(name: cd_name);

# cd.img_name = 'juusho'

# cd.save

# pp cd
